# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'Default'

steps:
- task: Maven@4
  inputs:
    jdkDirectory: jdk21
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'  # Changed from x64 to ARM64
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Check if the remote 'github' already exists, and update it if necessary
- script: |
    git remote remove github || true   # Remove the existing remote, if present
    git remote add github https://$(GITHUB_TOKEN)@github.com/gmmoreiracan/financial-planner-backend.git
  displayName: 'Add/Update GitHub remote'

- script: |
    git checkout $(Build.SourceBranch)
    git push github $(Build.SourceBranch)
  displayName: 'Sync changes to GitHub'

# Save the JAR file as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target/*.jar'
    ArtifactName: 'financial-planner-backend'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '**/surefire-reports/TEST-*.xml'
    ArtifactName: 'financial-planner-testresults'
