# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'Default'

steps:
- task: Maven@4
  inputs:
    jdkDirectory: jdk21
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'  # Changed from x64 to ARM64
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# - script: |
#     ls -la .
#     git clone https://github.com/gmmoreiracan/financial-planner-backend.git
#     ls -la .
#     git config --global user.name "Gabriel Moreira"
#     git checkout master
#     git add .
#     git commit -m "New changes from ADO"
#     git push https://$(GITHUB_TOKEN)@github.com/gmmoreiracan/financial-planner-backend.git HEAD:master
#   displayName: 'Sync changes to GitHub'

# Save the JAR file as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/financial-planner-backend-0.0.1-SNAPSHOT.jar'
    ArtifactName: 'financial-planner-backend'
    publishLocation: 'Container'