# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'Default'

jobs:
- job: BuildAndTest
  steps:
  - task: Maven@4
    inputs:
      jdkDirectory: jdk21
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64'  # Changed from x64 to ARM64
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  # Save the JAR file as an artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/target/financial-planner-backend-0.0.1-SNAPSHOT.jar'
      ArtifactName: 'financial-planner-backend-jar'
      publishLocation: 'Container'

- job: DeployToHeroku
  displayName: 'Deploy to Heroku'
  dependsOn: BuildAndTest
  condition: succeeded()

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Check if Heroku CLI is installed
        if ! command -v heroku &> /dev/null
        then
            echo "Heroku CLI not found, installing..."
            
            # Install Heroku CLI based on the OS
            if [[ "$OSTYPE" == "linux-gnu"* ]]; then
                curl https://cli-assets.heroku.com/install.sh | sh
            elif [[ "$OSTYPE" == "darwin"* ]]; then
                # macOS installation (Homebrew)
                brew tap heroku/brew && brew install heroku
            else
                echo "Unsupported OS for automatic Heroku installation"
                exit 1
            fi
        else
            echo "Heroku CLI already installed."
        fi

        # Check if already logged in
        if ! heroku auth:whoami &> /dev/null
        then
            echo "Not logged in, logging in..."
            heroku auth:token
        else
            echo "Already logged in to Heroku."
        fi

        heroku config:set JWT_SECRET=${JWT_SECRET} \
                       SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} \
                       SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL} \
                       SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} \
                       --app your-heroku-app-name
    displayName: 'Install and Authenticate Heroku CLI'

  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: 'financial-planner-backend-jar'
      targetPath: '$(Pipeline.Workspace)/target'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        heroku deploy:jar $(Pipeline.Workspace)/target/financial-planner-backend-0.0.1-SNAPSHOT.jar --app ${HEROKU_APP_NAME}
    displayName: 'Deploy JAR to Heroku'
    env:
      HEROKU_API_KEY: ${HEROKU_TOKEN}  # This should be set in your pipeline variables
