name: Sync to Azure DevOps
on:
  push:
    branches:
      - master  # Change to your branch if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Gabriel"
          git config --global user.email "gmmoreira.eng@gmail.com"  # Replace with your email

      - name: Add ADO Remote
        run: |
          git remote add ado https://${{ secrets.ADO_USERNAME }}:${{ secrets.ADO_PAT }}@dev.azure.com/gmmoreiracan/financial-planning/_git/financial-planning
          git fetch ado
        
      - name: Merge and push ADO changes
        run: |
          git checkout master
          git merge ado/master --allow-unrelated-histories -m "Merging ADO"
          git push ado master